'use strict';

/**
 * @ngdoc overview
 * @name miguApp
 * @description
 * # miguApp
 *
 * Main module of the application.
 */
angular
  .module('miguApp', [
  	'ui.bootstrap',
    'ngAnimate',
    'ui.router',
    'restangular',
    'ipCookie'
  ]).config(function($stateProvider,$urlRouterProvider){
  	$urlRouterProvider.otherwise('/main/fileDisplay');
  	$stateProvider
  		.state('main',{
  			url: '/main',
  			views:{
  				'indexView':{
  					templateUrl:'views/main.html',
  					controller:'mainCtrl'
  				}
  			}
  		}).state('main.fileDisplay',{
  			url:'/fileDisplay',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/arrival-detail.html',
  					controller:'arrivalDetailsCtrl'
  				}
  			}
  		}).state('main.error',{
  			url:'/error',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/error.html',
  					controller:'errorCtrl'
  				}
  			}
  		}).state('main.diff',{
  			url:'/diff',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/diff.html',
  					controller:'diffCtrl'
  				}
  			}
  		}).state('main.download',{
  			url:'/download',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/file-download.html',
  					controller:'downloadCtrl'
  				}
  			}
  		}).state('main.autoDownload',{
  			url:'/autoDownload',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/file-auto-download.html',
  					controller:'autoDownloadCtrl'
  				}
  			}
  		}).state('main.fileStatus',{
  			url:'/fileStatus',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/file-status.html',
  					controller:'fileStatusCtrl'
  				}
  			}
  		}).state('main.reProvince',{
  			url:'/reProvince',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/re-province.html',
  					controller:'reProvinceCtrl'
  				}
  			}
  		}).state('main.reZhiFuBao',{
  			url:'/reZhiFuBao',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/re-zhifubao.html',
  					controller:'reZhiFuBaoCtrl'
  				}
  			}
  		}).state('main.reDay',{
  			url:'/reDay',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/re-day.html',
  					controller:'reDayCtrl'
  				}
  			}
  		}).state('main.reMonth',{
  			url:'/reMonth',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/re-month.html',
  					controller:'reMonthCtrl'
  				}
  			}
  		}).state('main.reJiHe',{
  			url:'/reJiHe',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/re-jihe.html',
  					controller:'reJiHeCtrl'
  				}
  			}
  		}).state('main.formProvince',{
  			url:'/formProvince',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/form-province.html',
  					controller:'formProvinceCtrl'
  				}
  			}
  		}).state('main.formGlobal',{
  			url:'/formGlobal',
  			views:{
  				'mainView':{
  					templateUrl:'views/files/form-global.html',
  					controller:'formGlobalCtrl'
  				}
  			}
  		});
  });
